---
framework: "jasmine"
postMerge:
  pattern:
    - "./i18n/spec/*.js"
    - "./i18n/ucd/*.js"
preMerge:
  pattern:
    - "./i18n/spec/*.js"
    - "./i18n/ucd/*.js"
preRun:
  - yarn install
postRun:
  - yarn --version
  - yarn --version
version: 2.0
