---
framework: jasmine
blocklist:
  - "./src/calculator.test.js##Blacklist a test"
  - "./src/newFileTest.test.js##Comparision tests"
licenseTier: xsmall
postMerge:
  pattern:
    - "./i18n/spec/*.js"
    - "./i18n/ucd/*.js"
  strategy: 
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - "./i18n/spec/*.js"
    - "./i18n/ucd/*.js"
preRun:
     command:
        - yarn install
postRun:
     command:
        - yarn --version
version: 2.0
